### ISSUE TITLE
Could editor settings be added to the plugin, perhaps import them from VS Code?

### ISSUE THREAD

**Issue by YousufSSyed** [lukasbach/obsidian-code-files#10]
VS Code uses the Monaco editor and has a bunch of settings relating to the editor, like syntax highlighting colors. I'm wondering if its possible to import or even sync the settings to this plugin.

**Comment by lukasbach** [comment]
I like the idea, but I don't think it makes a lot of sense for this plugin. VSCode does structure settings in a different way that would make an import difficult, and also the obsidian dev community generally prefers plugins that only work within the file scope of one vault, not the entire file system (to prevent cross-platform issues, reduce dependency on general-purpose file system managers etc)
