### ISSUE TITLE
[Question] Is there a tutorial on how to self-host a monaco server?

### ISSUE THREAD

**Issue by peterzhu1992** [lukasbach/obsidian-code-files#15]
I try to host a monaco server myself with simpleserver.
Not seem to be able to reproduce what you have on your instance.

I would love to have this hosted myself, is there any tutorials you can share? Thanks.

**Comment by peterzhu1992** [comment]
Seems like you have some customized settings on your instance, mine does not onboard correctly:
```
<!DOCTYPE html>
<html>
  <head>
      <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
      <link
          rel="stylesheet"
          data-name="vs/editor/editor.main"
          href="../node_modules/monaco-editor/min/vs/editor/editor.main.css"
      />
  </head>
  <body>
      <!-- <div id="container" style="width: 800px; height: 600px; border: 1px solid grey"></div> -->
      <div id="container" style="width: 800px; height: 600px;"></div>

      <script>
          var require = { paths: { vs: '../node_modules/monaco-editor/min/vs' } };
      </script>
      <script src="../node_modules/monaco-editor/min/vs/loader.js"></script>
      <script src="../node_modules/monaco-editor/min/vs/editor/editor.main.nls.js"></script>
      <script src="../node_modules/monaco-editor/min/vs/editor/editor.main.js"></script>

      <script>
          var editor = monaco.editor.create(document.getElementById('container'), {
              value: [''].join('\n'),
              language: 'javascript'
          });
      </script>
  </body>
</html>

```

**Comment by peterzhu1992** [comment]
Ok I figured most things out where you send the context through urlparams.
Though I am still not sure how you send the file content through.
I am seeing a `Not allowed to load local resource` error where local files cannot be directly opened by the editor on my server.

**Comment by peterzhu1992** [comment]
Get it work with a local server hosting my files on localhost and use fetch to retrieve the content.

**Comment by lukasbach** [comment]
Happy to hear you got it to work. In case you need more help, here is the source code for the monaco instance that is used by the plugin: https://github.com/lukasbach/embeddable-monaco
