### ISSUE TITLE
Blank Extension Files

### ISSUE THREAD

**Issue by Aetherinox** [lukasbach/obsidian-code-files#17]
**Is your feature request related to a problem? Please describe.**
The ability to create a blank extension file for files without extensions

<br />

**Describe the solution you'd like**
I'm not even sure if this is possible due to how Obsidian is, but it would be nice to have files that don't have extensions such as files called `CaddyFile` or `.env`. These are yml files, however, the files don't contain extensions when used in Docker.

<br />

I've thought about how complicated this may be, and also found that the syntax highlighting works based on what extension you pick. So if this were to even be a thing, there would need to be a way to select what syntax highlighting to use somehow, otherwise you get a file filled with just white text.

<br />

**Describe alternatives you've considered**
Attempted to add a blank character to the list of file extensions
Added a file extension called `.env and then used a whitespace character for the filename

<br />

**Additional context**
![pinXwXx](https://github.com/lukasbach/obsidian-code-files/assets/118329232/fb3663f9-ce3b-43c4-ad9e-4ea2b0b2beec)

**Comment by lukasbach** [comment]
Unfortunately I don't think this is going to work any way, Obsidian only allows plugins to set up custom editors for certain file extensions, there is no way to configure Obsidian to associate a certain file pattern with a custom editor.
