### ISSUE TITLE
.tex extension color scheme

### ISSUE THREAD

**Issue by Huayra1** [lukasbach/obsidian-code-files#18]
**Is your feature request related to a problem? Please describe.**
As the files in code-files are automatically saved, it's brilliant for latex files that have a listener that compiles a pdf on file-save.
Obisidian code-files is therefore very good for working on .tex files.

**Describe the solution you'd like**
I would therefore like if there were some kind of color scheme for .tex files for easier editing.

**Describe alternatives you've considered**
Writing without any color scheme, though this makes it more difficult to read.

**Additional context**

**Comment by lukasbach** [comment]
Latex unfortunately isn't supported natively by Monaco Editor, and I'd rather not start with pulling VSCode Plugins into this package to support other languages, sorry.
