### ISSUE TITLE
How do I install this plugin?

### ISSUE THREAD

**Issue by DudeThatsErin** [lukasbach/obsidian-code-files#2]
I tried downloading the latest release and moving it to my plugins directory but I couldn't enable the plugin even after reloading Obisidian entirely.

I can't find it via the Community Plugins tab in Settings either.

This is all on a Windows Desktop.

**Comment by lukasbach** [comment]
I currently have an open PR on the obsidian-releases repo (https://github.com/obsidianmd/obsidian-releases/pull/1805), once that is through, the plugin will appear in the community plugins list.

For now, it should work by installing it manually, i.e. creating a folder `my-vault/.obsidian/plugins/code-files` and adding the files `main.js` and `manifest.json` into that folder from the latest release, and then reloading obsidian. 

If that is not working, I assume the plugin is failing to load, then I would be very interested in the error logs. In obsidian, can you please press `CTRL+i` and open the "Console" tab, and either send me a screenshot or right-click on any log line, click "Save as..." and send the created log file as attachement to this thread or to contact@lukasbach.com. Thanks!

**Comment by DudeThatsErin** [comment]
I was doing it wrong. Thank you!
