### ISSUE TITLE
Dark mode enhancement

### ISSUE THREAD

**Issue by likemuuxi** [lukasbach/obsidian-code-files#20]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when in Obsidian dark mode, code reading is very difficult

**Describe the solution you'd like**
Is it feasible to adjust the font color scheme

**Additional context**
![image](https://github.com/lukasbach/obsidian-code-files/assets/85612715/a551cc1c-32c3-4439-8c45-e3878f7e259a)

**Comment by lukasbach** [comment]
If the Obsidian Base Color Scheme is set appropriately, Code Files should switch the base theme automatically. What Base Color Theme and Theme Name (In Settings -> Appearance) do you have configured? (note that you will need to reopen the code file after switching a theme for the editor theme to adapt)

**Comment by likemuuxi** [comment]
Code Files did indeed switch the theme correctly and did not require a restart. I tried switching to the default theme and restarting to open the code file, but the code text was still difficult to read, I used the AnuPpuccin theme
![image](https://github.com/lukasbach/obsidian-code-files/assets/85612715/f6acb764-ba5e-485c-8618-acb2ce86488a)

**Comment by lukasbach** [comment]
Hm, I'm not sure what causes that. I installed the same theme and set it to dark mode, for me it uses other colors, i.e. the default vscode dark mode colors. Maybe you have some other plugins installed that mess with that? Or use a different obsidian version that doesn't support some theme APIs, I'm on v1.5.3 (Installer 1.4.13)...

![obsidian-editor-colormode](https://github.com/lukasbach/obsidian-code-files/assets/4140121/46d890a1-1023-4d00-ad4d-533b45a9356e)

**Comment by likemuuxi** [comment]
I am using the same version as you. I have created a new test library and only installed the Code Files plugin for troubleshooting. Unfortunately, the problem still exists, which is very confusing for me

**Comment by likemuuxi** [comment]
I understand the reason. In Obsidian, if the basic color is set to follow the system, the above problem will occur. Setting it to dark mode can restore normal operation. Thank you very much for your patience in answering. Can this problem be fixed

**Comment by Aetherinox** [comment]
Having the same issue, and all my other colors work fine.
My text with this plugin is black.

And after going through the code, it's handling the definitions for `mtk1` in such a way that even my overrides don't work. It refuses to use any other color and always takes priority.

**Comment by likemuuxi** [comment]
I solved this problem by using another plugin and making simple modifications to it. It is not appropriate to share it here without consent. You can leave your contact information and I will send it to you

**Comment by Aetherinox** [comment]
There's another plugin that does similar? Interesting.

If you would be kind enough to drop the info, click on my profile, and find my repo `obsidian-dataview-snippets `, then submit an issue. Don't want my email in public, I get enough spam already from scammers.

**Comment by lukasbach** [comment]
I've changed the way how themes are detected, thanks @likemuuxi for the details, that was very helpful in finding the culprit. It's fixed as of 1.1.6.

The plugin @likemuuxi mentioned is obsidian-vscode-editor. It's mostly just a rewrite of this plugin (e.g. see [my implementation of the settings in march last year](https://github.com/lukasbach/obsidian-code-files/commit/52062720087b7a324afc73ae36ef825bbccdccfa#diff-3dba939b04d1d8addb86738f5e7acefb94f5301c01e483d065b9efa981324b84), and [theirs implementation in september](https://github.com/sunxvming/obsidian-vscode-editor/commit/1dc51f329ad9c5f5635140103a7dbd181a8bd791#diff-3dba939b04d1d8addb86738f5e7acefb94f5301c01e483d065b9efa981324b84); or [my implementation of fence editing](https://github.com/lukasbach/obsidian-code-files/compare/4b53270430a42b466fc02a3f6df257a3c77c4646...88bea61ac982e3acd0145b2f67ae5f270812ce69) in september and [theirs in november](https://github.com/sunxvming/obsidian-vscode-editor/commit/eff8580f62e3d540350f5c62988ee50b376c7d49#diff-539e7d07159496dcfafd93a07dbfd4709dab235372dc3d573fd6b48e593985e2)). I'm fine with forking and improving things, though I'm not particularly happy with copying large parts of code bases without giving credit. Feel free to use that library if it works for your use case of course, though it's likely going to lack behing in new features whenever something new releases.

**Comment by likemuuxi** [comment]
The plugin is now working properly. Thank you for your work 🙌

**Comment by Aetherinox** [comment]
Awesome to hear.

**Comment by lukasbach** [comment]
Happy to hear. I've now also released the ability to choose from a few included custom themes, maybe that also helps with the customizability of things. Let me know if there are any issues with this.

![image](https://github.com/lukasbach/obsidian-code-files/assets/4140121/4a1f9682-47bd-462b-94b1-29a06148ddca)
