### ISSUE TITLE
vim mode

### ISSUE THREAD

**Issue by pelegm** [lukasbach/obsidian-code-files#22]
**Is your feature request related to a problem? Please describe.**
My Obsidian is vim-mode; when I get into the code editor, I'm not in vim mode anymore.

**Describe the solution you'd like**
It would be nice to stay in vim mode (as possible in VSCode).

**Describe alternatives you've considered**
Currently, I disable the plugin, and the code files are being opened by gvim.

**Comment by lukasbach** [comment]
I understand your use case, but unfortunately, since Monaco Editor doesn't have first-hand support for vim bindings, I'd rather not pull in additional dependencies for this, so I currently do not plan to bring support for this, sorry.
