### ISSUE TITLE
Is it possible to open code files like editing code blocks

### ISSUE THREAD

**Issue by likemuuxi** [lukasbach/obsidian-code-files#23]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when jump between notes and code files

**Describe the solution you'd like**
Open code files in a way similar to editing code blocks, If you feel it's unnecessary, please ignore my proposal.

**Describe alternatives you've considered**
I know you can use split screen to solve the problem of jumping between notes and code, but using this method on the small screen of a laptop is not comfortable

**Additional context**
![image](https://github.com/lukasbach/obsidian-code-files/assets/85612715/b3a0233f-9e48-4247-a98d-20aa0b9872eb)

**Comment by lukasbach** [comment]
Hi, thanks for your proposal. I'm not sure I understand the difference between what you propose and just using multiple tabs. You can keep your notes and a code file open in different tabs and switch from there, shouldn't that give you pretty much the same experience as opening a code note in a fullscreen popover?

**Comment by likemuuxi** [comment]
I often go back to the note file after browsing the code, perhaps because I often use the mouse for operations. I think opening the code file in a new tab and switching between tabs requires more operations. Perhaps using shortcut keys will be as you think. The following is an example of using a similar mode to open a webpage. I think after reading it, you should also think that this method is more convenient for browsing code.
![screenshots](https://github.com/lukasbach/obsidian-code-files/assets/85612715/112a4481-4eb3-4201-999d-c6411448a1ef)
![screenshots](https://github.com/lukasbach/obsidian-code-files/assets/85612715/d8442ef7-1d71-40e8-bc00-adcf307b16da)

**Comment by likemuuxi** [comment]
Perhaps I just want to unify my browsing style, which may have strong personal preferences, so this method is only for suggestion. You should decide how to define your plugin. Thank you again for your efforts in this excellent plugin

**Comment by lukasbach** [comment]
Hm, opening files located in a Obsidian vault in a dialog isn't a common UI pattern, so I rather wouldn't want to deviate from that, I hope you understand. But I'm happy you enjoy using the plugin.
