### ISSUE TITLE
BRAT install support?

### ISSUE THREAD

**Issue by vguillet** [lukasbach/obsidian-code-files#3]
And yet another MAJOR step for obsidian as a the best text editor on the planet! Thank you for your awsome work!

As the title says, any chance you plan to add BRAT support for easy installation?

**Comment by lukasbach** [comment]
Hey, thanks for your kind words! BRAT as in beta reviewers auto update tool? I haven't heard of it before, so not sure what is needed for a full setup there, but at least trying to add "lukasbach/obsidian-code-files" through the BRAT plugin in an sandbox vault worked fine for me. 

The proper easy installation method will be through the community plugins list once [obsidian-releases#1805](https://github.com/obsidianmd/obsidian-releases/pull/1805) is through.

**Comment by vguillet** [comment]
Indeed, but if it already works then that's perfect! Didn't see it appear in the doc so I assumed it wasn't an option (I was on mobile so didn't get a chance to test). Looking forward to the official release though!
