### ISSUE TITLE
No Autosave?

### ISSUE THREAD

**Issue by melMass** [lukasbach/obsidian-code-files#8]
**Describe the bug**
Editing a file, closing and reopening obsidian result in the file not being edited

**Expected behavior**
Autosaves as obsidian md files

**Additional context**
I discovered that as dataview was not updating my exported methods

**Screenshots**
![code_files_bug](https://github.com/lukasbach/obsidian-code-files/assets/7041726/872bcdc9-724e-437f-a27b-127f28e8e054)

**Only tested on Windows 11, I will try macOS ventura later today**

**Comment by lukasbach** [comment]
I added some additional logic for the editor to auto sync to the file.
